# from django.core.exceptions import ValidationError


class BotuserValidator:
    def __init__(self): ...

    def __call__(self):
        return True
